### ISSUE TITLE
Unfriendly error when just calling module from python

### ISSUE THREAD

**Issue by mkst** [Decompollaborate/spimdisasm#109]
```$ python3 -m spimdisasm 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mark/.local/lib/python3.8/site-packages/spimdisasm/__main__.py", line 12, in <module>
    exit(spimdisasm.frontendCommon.FrontendUtilities.cliMain())
  File "/home/mark/.local/lib/python3.8/site-packages/spimdisasm/frontendCommon/FrontendUtilities.py", line 257, in cliMain
    args = parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2047, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found```

**Comment by AngheloAlf** [comment]
What spimdisasm version do you have installed?

**Comment by mkst** [comment]
ah close this. guess I was on 1.11.x sorry :)
